routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\MessageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function (){
        return redirect(route('room.index'));
    });
    Route::get('/test', function () {
        return view('welcome');
    });
    Route::get('/trigger/{data}', function ($data) {
        event(new \App\Events\TestWebsocketEvent($data));
        return sprintf('傳送資料為%s',$data);
    });
    # Room
    Route::group(['middleware' => 'auth', 'prefix' => 'room', 'as' => 'room.'], function () {
        Route::get('/', [RoomController::class, 'index'])->name('index');
        Route::get('/event', [RoomController::class, 'event'])->name('event');
        Route::get('/create', [RoomController::class, 'create'])->name('create');
        Route::get('/{id}/edit', [RoomController::class, 'edit'])->name('edit');
        Route::get('{id}', [RoomController::class, 'chat'])->name('chat');
        Route::post('/store', [RoomController::class, 'store'])->name('store');
        Route::post('/{id}/join', [RoomController::class, 'join'])->name('join');
        Route::put('/{id}/update', [RoomController::class, 'update'])->name('update');
        Route::put('/{id}/join', [RoomController::class, 'joinRoom'])->name('join.room');
        # Message
        Route::post('/{id}/message', [MessageController::class, 'store'])->name('message');
        Route::post('/{id}/message/typing', [MessageController::class, 'typing'])->name('message.typing');
        Route::post('/{id}/message/clean', [MessageController::class, 'clean'])->name('message.clean');
    });
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\SoftDeletes;

class Room extends Model
{
    use SoftDeletes;
    /**
     * @var string
     */
    protected $table = 'room';

    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    protected $fillable = [
        'user_id',
        'title',
        'created_at',
        'updated_at',
        'is_private',
        'cipher',
        'cover',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     * @Author: Roy
     * @DateTime: 2021/10/23 下午 02:03
     */
    public function message()
    {
        return $this->hasMany(Message::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     * @Author: Roy
     * @DateTime: 2021/10/23 下午 02:03
     */
    public function room_join()
    {
        return $this->hasMany(RoomJoin::class, 'room_id', 'id');
    }

    /**
     * @param  int  $room_id
     *
     * @return mixed
     * @Author: Roy
     * @DateTime: 2021/11/29 下午 03:58
     */
    public function getRoomMessage(int $room_id)
    {
        return $this
            ->with([
                'message'=>function($messageQuery){
                    return $messageQuery->with('user');
                },
                'room_join',
            ])
            ->whereHas('room_join',function ($query) use($room_id){
                return $query
                    ->where('room_id',$room_id)
                    ->where('user_id',Auth::id())
                ;
            })
            ->find($room_id)
        ;
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRoom;
use App\Models\Room;
use App\Models\RoomJoin;
use App\Models\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use App\Events\RoomChannelEvent;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Hash;
use App\Events\RoomMessageChannelEvent;
use Carbon\Carbon;

class RoomController extends Controller
{
    /**
     * @var Room
     */
    public $model;

    /**
     * @var RoomJoin
     */
    public $join;

    /**
     * @var Message
     */
    public $message;

    /**
     * RoomController constructor.
     *
     * @param  Room  $room
     * @param  RoomJoin  $join
     * @param  Message  $message
     */
    public function __construct(Room $room, RoomJoin $join, Message $message)
    {
        $this->model = $room;
        $this->join = $join;
        $this->message = $message;
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     * @Author: Roy
     * @DateTime: 2021/10/22 下午 04:29
     */
    public function index()
    {
        $rooms = $this->model->paginate(config('room.page_size'));
        $paginate = $rooms->links('pagination.default');
        $rooms = $rooms->map(function ($room) {
            return (object) [
                'id'         => Arr::get($room, 'id'),
                'title'      => Arr::get($room, 'title'),
                'cover'      => asset(Arr::get($room, 'cover', config('room.default_room_pic'))),
                'user_id'    => Arr::get($room, 'user_id'),
                'is_private' => Auth::id() == Arr::get($room, 'user_id') ? false : Arr::get($room, 'is_private'),
                'cipher'     => Arr::get($room, 'cipher'),
                'actions'    => (object) [
                    'join_uri' => route('room.join.room', [
                        'id' => $room->id,
                    ]),
                ],
            ];
        });
        return view('room.lists', ['rooms' => $rooms, 'paginate' => $paginate]);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     * @Author: Roy
     * @DateTime: 2021/10/24 下午 11:18
     */
    public function create()
    {
        return view('room.add');
    }

    /**
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     * @Author: Roy
     * @DateTime: 2021/10/24 下午 11:18
     */
    public function edit(Request $request)
    {
        # 判断是否存在
        $roomEntity = $this->checkAndGet($request->id);
        # 判断是否有权限
        if ($roomEntity->user_id != $request->user()->id) {
            abort(403, '无权操作');
        }
        $room = (object) [
            'id'         => Arr::get($roomEntity, 'id'),
            'title'      => Arr::get($roomEntity, 'title'),
            'cover'      => asset(Arr::get($roomEntity, 'cover', config('room.default_room_pic'))),
            'user_id'    => Arr::get($roomEntity, 'user_id'),
            'is_private' => Arr::get($roomEntity, 'is_private'),
            'cipher'     => Arr::get($roomEntity, 'cipher'),
        ];
        return view('room.edit', ['room' => $room]);
    }

    /**
     * @param  \App\Http\Requests\StoreRoom  $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @Author: Roy
     * @DateTime: 2021/10/24 下午 11:18
     */
    public function store(StoreRoom $request)
    {
        $file = $request->file('cover');
        $data = [
            'title'      => $request->get('title'),
            'is_private' => $request->get('isPrivate'),
            'cipher'     => $request->get('cipher') ? bcrypt($request->get('cipher')) : '',
            'user_id'    => $request->user()->id,
        ];
        # 封面照
        if ($file) {
            $data['cover'] = sprintf('storage/%s', Storage::disk('public')->putFile(date('Y/m'), $file));
        }
        # 新增
        $roomEntity = $this->model->create($data);
        # room_join
        $roomEntity->room_join()->create(['room_id' => $roomEntity->id, 'user_id' => $request->user()->id]);

        event((new RoomChannelEvent()));
        return redirect(route('room.index'))->with('message', 'created success');
    }

    /**
     * @param  \App\Http\Requests\StoreRoom  $request
     * @param $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @Author: Roy
     * @DateTime: 2021/10/24 下午 11:18
     */
    public function update(StoreRoom $request, $id)
    {

        $file = $request->file('cover');
        $data = [
            'title'      => $request->get('title'),
            'is_private' => $request->get('isPrivate'),
            'cipher'     => $request->get('cipher') ? bcrypt($request->get('cipher')) : '',
            'user_id'    => $request->user()->id,
        ];
        # 封面照
        if ($file) {
            $data['cover'] = sprintf('storage/%s', Storage::disk('public')->putFile(date('Y/m'), $file));
        }
        $this->model->find($id)->update($data);
        event((new RoomChannelEvent()));
        return redirect(route('room.index'))->with('message', 'updated success');
    }


    /**
     * @param $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     * @Author: Roy
     * @DateTime: 2021/10/24 下午 11:18
     */

    public function chat($id)
    {
        # 判斷房間是否存在
        $room = $this->model->getRoomMessage($id);
        # 判斷用戶是否加入
        if (is_null($room) === true) {
            abort(404, '請返回列表重新加入房間');
        }
        $latestMessages = $room->message->groupBy('date');
        $latestMessages = $latestMessages->map(function ($messages, $dates) {
            return $messages->map(function ($message) {
                return (object) [
                    'content'    => (Arr::get($message, 'content')),
                    'user_name'  => Arr::get($message, 'user_name'),
                    'user_image' => sprintf("https://ui-avatars.com/api/?name=%s&color=7F9CF5&background=EBF4FF",
                        $message->user->name),
                    'class'      => Auth::user()->id == $message->user_id ? 'right' : 'left',
                    'time'       => $message->created_at->format('H:i'),
                ];
            });
        });

        return view('room.chat',
            [
                'room'      => $room,
                'messages'  => $latestMessages,
                'memberNum' => $room->room_join->count(),
            ]
        );
    }

    /**
     * @param  \Illuminate\Http\Request  $request
     * @param $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @Author: Roy
     * @DateTime: 2021/10/25 上午 10:07
     */
    public function join(Request $request, $id)
    {
        $room = $this->checkAndGet($id);
        # 已加入
        if ($this->join->checkUserJoined($id, $this->join) || Auth::user()->id == $room->user_id) {
            return redirect(route('room.chat', ['id' => $id]));
        }
        # 密碼
        if ($room->isPrivate) {
            return redirect(route('room.index'))->with('modal', '请输入密码');
        }
        # 加入
        $this->join->create([
            'user_id' => Auth::user()->id,
            'room_id' => $id,
        ]);
        return redirect(route('room.chat', ['id' => $id]))->with('message', 'joined success');
    }

    /**
     * @param $id
     * @param  string  $message
     *
     * @return mixed
     * @Author: Roy
     * @DateTime: 2021/10/24 下午 11:17
     */
    public function checkAndGet($id, $message = '')
    {
        $info = $this->model->find($id);
        if (!$info) {
            abort(404, $message ? $message : "This {$this->model->getTable()} does not exist.");
        }
        return $info;
    }

    /**
     * @param  \Illuminate\Http\Request  $request
     * @param $id
     *
     * @return \Illuminate\Http\JsonResponse
     * @Author: Roy
     * @DateTime: 2021/10/22 下午 04:26
     */
    public function joinRoom(Request $request, $id)
    {
        $room = $this->checkAndGet($id);
        # 已加入
        if ($this->join->checkUserJoined($id, $this->join) || Auth::user()->id == $room->user_id) {
            return response()->json([
                'status'       => true,
                'message'      => 'have joined',
                'redirect_uri' => route('room.chat', ['id' => $id]),
            ]);
        }
        # 密碼
        if ($room->is_private && !Hash::check($request->cipher, $room->cipher)) {
            return response()->json(['status' => false, 'message' => '密碼不正確']);
        }

        $this->join->create([
            'user_id' => Auth::user()->id,
            'room_id' => $id,
        ]);

        return response()->json([
            'status'       => true,
            'message'      => 'joined success',
            'redirect_uri' => route('room.chat', ['id' => $id]),
        ]);
    }

}

resources/views/room/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create</div>

                    <div class="panel-body">
                        <form class="form-horizontal" enctype="multipart/form-data" method="POST"
                              action="{{route('room.store')}}">
                            @method('post')
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-4 control-label">名稱</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control" name="title"
                                           value="{{ old('title') }}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group {{ $errors->has('cover') ? ' has-error' : '' }}">
                                <label for="cover" class="col-md-4 control-label">封面</label>

                                <div class="col-md-6">
                                    <input type="file" id="cover" name="cover" value="{{ old('cover') }}" accept="image/*">

                                    @if ($errors->has('cover'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('cover') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group {{ $errors->has('isPrivate') ? ' has-error' : '' }}">
                                <label for="isPrivate" class="col-md-4 control-label">是否私密</label>

                                <div class="col-md-6">
                                    <label class="radio-inline">
                                        <input type="radio" class="isPrivate" name="isPrivate" value="0" checked> 否
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" class="isPrivate" name="isPrivate" value="1"> 是
                                    </label>

                                    @if ($errors->has('isPrivate'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('isPrivate') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group hidden {{ $errors->has('cipher') ? ' has-error' : '' }}"
                                 id="cipherDiv">
                                <label for="cipher" class="col-md-4 control-label">密碼</label>

                                <div class="col-md-6">
                                    <input id="cipher" type="password" class="form-control" name="cipher" autofocus>

                                    @if ($errors->has('cipher'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('cipher') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ asset('js/rooms/form.js?v='.config('app.version')) }}"></script>
@endsection

resources/views/room/chat.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{asset('css/chat.css')}}?v={{config('app.version')}}">
    <div class="container">
        <div class="row">
            @if($room->user_id == \Illuminate\Support\Facades\Auth::id())
            <a class="btn btn-primary" id="clean">清除</a>
            @endif
            <div class="col-md-8 col-md-offset-2">
                <div class="row">
                    {{--room start--}}
                    <div class="col-sm-12 col-md-12">
                        <div class="thumbnail">

                            <div class="caption">
                                {{--頭部--}}
                                <h4>{{$room->title}} <span class="pull-right number">(<span class="online"
                                        >0</span>/<span class="all">{{$memberNum}}</span>)
                                    </span></h4>
                                {{--内容--}}
                                <div class="content">
                                    @foreach($messages as $key => $dateMessages)
                                        <span class="joined">{{\Illuminate\Support\Carbon::today()->toDateString() == $key ? 'Today':$key}}</span>
                                        @foreach($dateMessages as $message)
                                        <div
                                            class="chat-{{$message->class}}">
                                            <img src="{{$message->user_image}}" alt="{{$message->user_name}}"
                                                 class="avatar pull-{{$message->class}}">
                                            <div
                                                class="pull-{{$message->class}}">
                                                <span class="username username-{{$message->class}}">{{$message->user_name}}</span>
                                                <br>
                                                <div>
                                                    <span class="content-span">{!!$message->content!!}</span>
                                                    <span class="timestamp-{{$message->class}}">{{$message->time}}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                        @endforeach
                                    @endforeach
                                </div>
                                {{--正在輸入--}}
                                <div class="typing"></div>
                                {{--底部--}}
                                <div class="form-group">
                                    <textarea onblur="leftFocus();" onfocus="joinFocus();" id="content"
                                              class="form-control wait-send" rows="3"></textarea>
                                </div>
                                <button class="btn btn-primary pull-right"
                                        role="button" id="send">送出
                                </button>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    {{--room end--}}
                    <span class="default-value hide" data-default-avatar="{{config('room.default_avatar')}}"
                          data-user-id="{{Auth::user()->id}}" data-room-id="{{$room->id}}"></span>
                </div>
            </div>
        </div>
    </div>
    <script src="{{asset('js/rooms/room.js?v='.config('app.version'))}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/3.0.0/mustache.min.js"></script>
    <script type="text/x-mustache" id="template">
    <div
        class="chat-@{{ direction }}">
        <img src="@{{ user_image }}" alt="@{{ user_name }}"
             class="avatar pull-@{{ direction }}">
        <div
            class="pull-@{{ direction }}">
            <span
                class="username username-@{{ direction }}">@{{ user_name }}</span>
            <br>
            <span class="content-span">@{{ content }}</span>
            <span class="timestamp-@{{ direction }}">@{{ time }}</span>
        </div>
    </div>
    <div class="clearfix"></div>
    </script>
    <script type="text/x-mustache" id="typing_template">
        <span id="typing">@{{ name }}正在輸入...</span>
    </script>
    <script>
        let user_id = {{Auth::user()->id}};
        let room_id = {{$room->id}};
        let message_uri = '{{route('room.message',['id'=>$room->id])}}';
        let typing_uri = '{{route('room.message.typing',['id'=>$room->id])}}';
        let status_blur = {{\App\Constants\TypingStatus::TypingStatus_Blur}};
        let status_focus = {{\App\Constants\TypingStatus::TypingStatus_Focus}};
        let message_clean_uri = '{{route('room.message.clean',['id'=>$room->id])}}';
    </script>
@endsection

resources/views/room/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit</div>

                <div class="panel-body">
                    <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{{route('room.update',['id'=>$room->id])}}">
                        {{ csrf_field() }}
                        @method('put')
                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-4 control-label">名稱</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control" name="title" value="{{ old('title') ?? $room->title }}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group {{ $errors->has('cover') ? ' has-error' : '' }}">
                            <label for="cover" class="col-md-4 control-label">封面</label>

                            <div class="col-md-6">
                                <input type="file" id="cover" name="cover" value="{{ old('cover') }}" accept="image/*">

                                @if ($errors->has('cover'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('cover') }}</strong>
                                    </span>
                                @endif

                                @if($room->title)
                                    <img src="{{$room->cover}}"
                                         alt="{{$room->title}}">
                                @endif
                            </div>
                        </div>

                        <div class="form-group {{ $errors->has('isPrivate') ? ' has-error' : '' }}">
                            <label for="isPrivate" class="col-md-4 control-label">是否私密</label>

                            <div class="col-md-6">
                                <label class="radio-inline">
                                    <input type="radio" class="isPrivate" name="isPrivate" value="0" {{$room->is_private == 0 ? "checked" : ""}}> 否
                                </label>
                                <label class="radio-inline">
                                    <input type="radio" class="isPrivate" name="isPrivate" value="1" {{$room->is_private == 1 ? "checked" : ""}} > 是
                                </label>

                                @if ($errors->has('isPrivate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('isPrivate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group {{$room->is_private == 1 ? 'show' : 'hidden'}} {{ $errors->has('cipher') ? ' has-error' : '' }}" id="cipherDiv">
                            <label for="cipher" class="col-md-4 control-label">密碼</label>

                            <div class="col-md-6">
                                <input id="cipher" type="password" class="form-control" name="cipher" autofocus>

                                @if ($errors->has('cipher'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('cipher') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ asset('js/rooms/form.js?v='.config('app.version')) }}"></script>
@endsection

<style>
    img {
        height: 150px;
    }
</style>